version: 3

tasks:
  test:
    cmd: uv run pytest tests --doctest-modules --junitxml=junit/test-results.xml
    desc: Run tests

  jhub:
    cmd: uv run --with jupyter jupyter lab
    desc: Run Jupyter Lab

  lint:
    cmd: uv run ruff check
    desc: Run linter

  lint-fix:
    cmd: uv run ruff check --fix
    desc: Run linter and fix issues

  format:
    cmd: uv run ruff format
    desc: Format code

  format-check:
    cmd: uv run ruff format --check
    desc: Check if code is formatted
