[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "pillow>=11.1.0",
    "tensorflow>=2.18.0",
    "uvicorn>=0.34.0",
]
