name: Base CI

on: [push, pull_request]

jobs:
  base:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run lint
        run: task lint

      - name: Run format check
        run: task format-check

      - name: Run tests
        run: task test

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results.xml
        if: ${{ always() }}
